---
# yamllint disable rule:line-length
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8 # v1.5.6
    hooks:
      - id: forbid-tabs
        exclude_types: [python, javascript, dtd, markdown, makefile, xml]
        exclude: binary|\.bin$
  - repo: https://github.com/jameswoolfenden/pre-commit-shell
    rev: 062f0b028ae65827e04f91c1e6738cfcbe9b337f # v1.0.6
    hooks:
      - id: shell-lint
        exclude: template|\.template$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: a4d5d37e66ebcd6b3705204a1d6dbb56dea66338 # v0.49.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/jameswoolfenden/pre-commit
    rev: c5bdf92051a9e574d62152d81a3bd98a71816dd3 # v0.1.62
    hooks:
      - id: terraform-fmt
      - id: tf2docs
  - repo: https://github.com/bridgecrewio/checkov
    rev: 7e4d52326380c54f2d9ad33fa8991933bc6d8c46 # 3.3.8
    hooks:
      - id: checkov
        verbose: true
        entry: checkov -d example/examplea --external-checks-dir checkov --download-external-modules true --compact
  - repo: https://github.com/jameswoolfenden/pike
    rev: b5e01747b43908cc995feaa2843a3ed9562c488d # v1.0.7
    hooks:
      - id: pike-docs-go
        args: ["readme","-i","-d", "."]
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/jameswoolfenden/ghat
    rev: 23f983caae0cc73d67f16f691dc47211488f5dc1 # v0.1.46
    hooks:
      - id: ghat-go
      - id: ghat-go-sift
