---
name: Verify and Bump
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: master
          token: ${{ github.token }}
      - uses: hashicorp/setup-terraform@master
      - name: Terraform Init
        id: init
        run: terraform init example/examplea
      - name: Terraform Validate
        id: validate
        run: terraform validate example/examplea
      - name: Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "example/examplea"
          framework: terraform
      - name: Terraform Apply
        if: ${{ !env.ACT }}
        id: apply
        run: terraform apply example/examplea -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Destroy
        if: ${{ !env.ACT }}
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  version:
    name: versioning
    if: ${{ !env.ACT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
    needs: build
