---
name: Verify and Bump
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ github.token }}
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.0
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "example/examplea"
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.0
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "example/examplea"
      - name: Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "example/examplea"
          framework: terraform
      - name: Terraform Apply
        if: ${{ !env.ACT }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.0
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "example/examplea"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Destroy
        if: ${{ !env.ACT }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.0
          tf_actions_subcommand: "destroy"
          tf_actions_working_dir: "example/examplea"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  version:
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        if: ${{ !env.ACT }}
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
    needs: build
