---
name: pull_request
on: pull_request
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ github.token }}
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "example/examplea"
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "example/examplea"
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ github.token }}

      - name: Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "example/examplea"
          framework: terraform
          args: "--output cli  --bc-api-key ${{ secrets.BC_API_KEY }}"
